=== usnistgov/NIST-Decision-Tree/example_post_requests/run_ndt_json_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "laboratory": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 3
    },
    "measured_values": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 3
    },
    "std_unc": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 3
    },
    "dof:rep": {
      "type": "array",
      "items": {
        "type": "integer"
      },
      "minItems": 0
    },
    "exclude": {
      "type": "array",
      "items": {
        "type": "boolean"
      },
      "minItems": 0
    },
    "procedure": {
      "type": "string"
    },
    "num_bootstrap": {
      "type": "integer"
    },
    "seed": {
      "type": "integer"
    },
    "n_iter": {
      "type": "integer"
    },
    "burn_in": {
      "type": "integer"
    }
  },
  "required": [
    "laboratory",
    "measured_values",
    "std_unc"
  ],
  "additionalProperties": false
}

=== usnistgov/NIST-Decision-Tree/example_post_requests/example1.json
{
    "laboratory":["Lab1","Lab2","Lab3","Lab4","Lab5"],
    "measured_values":[1,3,5,4,2],
    "std_unc":[1,2,1,2,1],
    "dof:rep":[30,30,30,30,30],
    "exclude":[false,false,false,false,false],
    "procedure":"Recommended",
    "num_bootstrap":1000,
    "seed":123,
    "n_iter":50000,
    "burn_in":25000
}
